version: 2
jobs:
           build:
                        docker:
                                       - image: circleci/<bash>:<2>
                                              steps:
                                                             - checkout
                                                                      - run: echo "hello"

